### ISSUE TITLE
As a developer I want to make my project REUSE compliant as fast as possible using FLIGHT RULES

### ISSUE THREAD

**Issue by Piiit** [idm-suedtirol/reuse#1]
We need flight rules for that :-)

- [x] Describe what flight rules are in general
- [x] I want to check if my project is REUSE compliant
- [x] I want to know which license a certain file has
- [x] I want to make my GPL-3 project REUSE compliant
- [x] I want to make my multi-license project REUSE compliant
- [x] I want to add a comment header to each file
- [x] I want to add a comment header to each file in my Maven/Java project
- [x] I want to define a pattern to associate various files to a license
- [x] I want to exclude some files from REUSE compliance checking

**Comment by Piiit** [comment]
@ohnewein @karmaran Done. Please read them and tell what you think about spelling, grammar, and content. Any feedback welcome :-)

See https://github.com/idm-suedtirol/reuse/blob/master/README.md

**Comment by karmaran** [comment]
What do you think about adding a sentence like
 ¨If you have not decided yet about which license are going to choose, give a look here https://choosealicense.com/ (hyperlink of course)¨  
The link gives a short overview of the most common licenses and is curated by GitHub.
I would add it maybe at the end of the section of ¨I want to make my GPL-3 project REUSE compliant¨ or would it be off topic?

**Comment by Piiit** [comment]
@karmaran Good idea. I will add it.

**Comment by Piiit** [comment]
Done. See https://github.com/idm-suedtirol/reuse/commit/14b078b4f037674e0714086f481b5eb9bfc215e4 for changes...
