### ISSUE TITLE
I need a FSFE account to contribute to the reuse project

### ISSUE THREAD

**Issue by Piiit** [idm-suedtirol/reuse#6]
@ohnewein Is that possible with IDM, or must it be done personally?

**Comment by ohnewein** [comment]
@Piiit I don't understand what exactly is needed. Can't you just clone the reuse repo without having an account on the FSFE gitea server?

**Comment by Piiit** [comment]
@ohnewein I thought of directly contribute to the project, we could create issues and pull-requests... I have seen that a German and Italian translation is missing for instance...

**Comment by Piiit** [comment]
Done.
